### ISSUE TITLE
size mismatch on import

### ISSUE THREAD

**Issue by sferik** [technoweenie/madrox#2]
https://gist.github.com/489e161f8bbf9a18ad1d

**Comment by weppos** [comment]
I'm experiencing the same error.

**Comment by pthrasher** [comment]
Yep, same here... Just started out of nowhere.

**Comment by razielgn** [comment]
I looked into this with pry and it looks like it's an encoding problem.
For example, when I have a tweet with the character `ì` in it, the char gets encoded as `\xC3\xAC` making the actual content length longer and thus raising the exception.

**Comment by pthrasher** [comment]
Ahh... So this is a unicode issue with GRIN, then?

**Comment by razielgn** [comment]
Looks like it, yes.

**Comment by lenage** [comment]
can someone fixed this?

**Comment by pthrasher** [comment]
@lenage It's a bug with grit.

There's two related issues:
mojombo/grit#51
mojombo/grit#65

**Comment by lenage** [comment]
@pthrasher  thanks! very helpful

**Comment by nandub** [comment]
I made the changes to the vendor/grit using mojombo/grit#51, now i don't get this error.

**Comment by pthrasher** [comment]
Yeah, I wish they'd do an official release so that it could be updated with this tool.

**Comment by technoweenie** [comment]
Madrox 0.3 is out now, with a dependency on grit 2.5.0.
