### ISSUE TITLE
Missing dependancies?

### ISSUE THREAD

**Issue by Psycojoker** [technoweenie/madrox#3]
Disclosure: I have a very low level of knowledge of the ruby technologies.

Ohai,

I've install madrox from rubygems but I couldn't managed to make it works without also installing diff-lcs and mime-types. Shoudln't those two be in the dependancies pulled by this gem?

Regards,

**Comment by technoweenie** [comment]
Ah, it normally would.  I vendored an experimental version of grit though, and that stopped it from installing dependencies.  I should probably take that out and add grit as a dependency.

**Comment by Psycojoker** [comment]
Well, I'll let you choose, can't tell what is the best.

Also, I've forgot to add but I was doing this on an ubuntu distribution, I know they are doing some special stuff with gem but I don't think this should influence this issue.

**Comment by Psycojoker** [comment]
This issue still hasn't been revolved, a friend of mine just told he've got the same problem than me.

**Comment by technoweenie** [comment]
Grit has been updated to v2.5.0.  The problems should be gone now.

**Comment by Psycojoker** [comment]
Ok, thx :)
